Repository enjarai/trickster, pull requests merged in 2025-03, with the labels that each got.

#99 This is certainly something isn't it
  src/client/java/dev/enjarai/trickster/TricksterClient.java
  src/client/java/dev/enjarai/trickster/render/MerlinKeeperTracker.java
  src/main/generated/.cache/27614340de28b382d5f7ae74366bcf39e2ac3aeb
  src/main/generated/.cache/3ac65fa3d3c37fa00307c1168fcecdd37a25c66a
  src/main/generated/.cache/61708f0ed37294451167e111af3b2b862215b6f8
  src/main/generated/.cache/79ef07c0320f2b1bff073a33f581b6ea484cf452
  src/main/generated/.cache/de828e1c0b483619cb31befb2371ade13f1a18a1
  src/main/generated/.cache/f158030e12b0d9d4165e4586179e424d8925bffa
  src/main/generated/assets/trickster/models/item/collar.json
  src/main/generated/assets/trickster/models/item/leash.json
  src/main/java/dev/enjarai/trickster/Trickster.java
  src/main/java/dev/enjarai/trickster/cca/CasterComponent.java
  src/main/java/dev/enjarai/trickster/datagen/ModModelGenerator.java
  src/main/java/dev/enjarai/trickster/item/CollarItem.java
  src/main/java/dev/enjarai/trickster/item/LeashItem.java
  src/main/java/dev/enjarai/trickster/item/ModItems.java
  src/main/java/dev/enjarai/trickster/item/component/CollarLinkComponent.java
  src/main/java/dev/enjarai/trickster/item/component/ModComponents.java
  src/main/java/dev/enjarai/trickster/mixin/ItemMixin.java
  src/main/resources/assets/trickster/lang/en_us.yml
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/leash_and_collar.md
  src/main/resources/assets/trickster/textures/item/collar.png
  src/main/resources/assets/trickster/textures/item/leash.png
  src/main/resources/data/accessories/tags/item/necklace.json
  src/main/resources/data/minecraft/tags/item/enchantable/equippable.json
  src/main/resources/data/trickster/advancement/trigger/collar.json
  src/main/resources/data/trickster/recipe/collar.json
  src/main/resources/data/trickster/recipe/leash.json
  src/main/resources/data/trickster/tags/item/collars.json
  src/main/resources/data/trickster/tags/item/curseable.json
Labels: enhancement

#100 Levitating Blocks
  src/client/java/dev/enjarai/trickster/TricksterClient.java
  src/client/java/dev/enjarai/trickster/render/entity/LevitatingBlockEntityRenderer.java
  src/main/java/dev/enjarai/trickster/Trickster.java
  src/main/java/dev/enjarai/trickster/entity/LevitatingBlockEntity.java
  src/main/java/dev/enjarai/trickster/entity/ModEntities.java
  src/main/java/dev/enjarai/trickster/mixin/EntityMixin.java
  src/main/java/dev/enjarai/trickster/spell/trick/entity/ChangeWeightTrick.java
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/ploys/block.md
Labels: enhancement

#117 Improve glyph drawing
  src/client/java/dev/enjarai/trickster/render/SpellCircleRenderer.java
  src/client/java/dev/enjarai/trickster/screen/SpellPartWidget.java
  src/main/java/dev/enjarai/trickster/config/TricksterConfigModel.java
  src/main/resources/assets/trickster/lang/en_us.yml
Labels: bug, enhancement

#119 Add Deviations as a new type of trick and solidify Stratagems as variadic Distortions
  src/main/generated/.cache/27614340de28b382d5f7ae74366bcf39e2ac3aeb
  src/main/generated/.cache/3ac65fa3d3c37fa00307c1168fcecdd37a25c66a
  src/main/generated/.cache/61708f0ed37294451167e111af3b2b862215b6f8
  src/main/generated/.cache/79ef07c0320f2b1bff073a33f581b6ea484cf452
  src/main/generated/.cache/de828e1c0b483619cb31befb2371ade13f1a18a1
  src/main/generated/.cache/f158030e12b0d9d4165e4586179e424d8925bffa
  src/main/java/dev/enjarai/trickster/advancement/criterion/ModCriteria.java
  src/main/java/dev/enjarai/trickster/advancement/criterion/UseCostPloyCriterion.java
  src/main/java/dev/enjarai/trickster/spell/trick/basic/CostTrick.java
  src/main/resources/assets/trickster/lang/en_us.yml
  src/main/resources/assets/trickster/lavender/categories/tome_of_tomfoolery/distortions.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/concepts/tricks_explanation.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/delusions_ingresses/entity.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/distortions/list.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/distortions/map.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/distortions/tree.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/astral_hint.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/astral_knot.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/cracked_echo_knot.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/echo_knot.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/ominous_spell_core.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/rusted_spell_core.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/ploys/misc.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/tricks/basic.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/tricks/cost.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/tricks/functions.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/tricks/imports.md
  src/main/resources/data/trickster/advancement/cost_ploy.json
Labels: documentation

#116 editor key interactions
  src/client/java/dev/enjarai/trickster/screen/ScrollAndQuillScreen.java
Labels: enhancement

#118 Refactor spell view
  src/client/java/dev/enjarai/trickster/render/SpellCircleRenderer.java
  src/client/java/dev/enjarai/trickster/screen/ScrollAndQuillScreen.java
  src/client/java/dev/enjarai/trickster/screen/SpellPartWidget.java
  src/main/java/dev/enjarai/trickster/spell/SpellPart.java
Labels: bug

#113 Whorl config
  src/main/java/dev/enjarai/trickster/config/TricksterConfigModel.java
  src/main/java/dev/enjarai/trickster/item/ManaAccessory.java
  src/main/resources/assets/trickster/lang/en_us.yml
Labels: enhancement
