Repository enjarai/trickster, pull requests merged in 2025-01, with the labels that each got.

#82 Fuck
  src/client/java/dev/enjarai/trickster/ModKeyBindings.java
  src/client/java/dev/enjarai/trickster/mixin/client/InGameHudMixin.java
  src/client/java/dev/enjarai/trickster/pond/QuackingInGameHud.java
  src/client/java/dev/enjarai/trickster/render/FunnyStaticFrameBufferThing.java
  src/main/java/dev/enjarai/trickster/TricksterCommand.java
  src/main/java/dev/enjarai/trickster/cca/EntityScaleComponent.java
  src/main/java/dev/enjarai/trickster/cca/EntityWeightComponent.java
  src/main/java/dev/enjarai/trickster/cca/ModEntityComponents.java
  src/main/java/dev/enjarai/trickster/item/ModItems.java
  src/main/java/dev/enjarai/trickster/item/TrickHatItem.java
  src/main/java/dev/enjarai/trickster/item/component/ManaComponent.java
  src/main/java/dev/enjarai/trickster/mixin/LivingEntityMixin.java
  src/main/java/dev/enjarai/trickster/net/LoadExampleSpellPacket.java
  src/main/java/dev/enjarai/trickster/net/ScrollHatPacket.java
  src/main/java/dev/enjarai/trickster/spell/SpellContext.java
  src/main/java/dev/enjarai/trickster/spell/blunder/NumberTooLargeBlunder.java
  src/main/java/dev/enjarai/trickster/spell/trick/Tricks.java
  src/main/java/dev/enjarai/trickster/spell/trick/entity/AddVelocityTrick.java
  src/main/java/dev/enjarai/trickster/spell/trick/entity/ChangeWeightTrick.java
  src/main/java/dev/enjarai/trickster/spell/trick/entity/GetScaleTrick.java
  src/main/java/dev/enjarai/trickster/spell/trick/entity/SetScaleTrick.java
  src/main/resources/assets/trickster/lang/en_us.yml
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/delusions_ingresses/raycast.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/ploys/entity.md
  src/main/resources/data/trickster/tags/item/scroll_and_quills.json
  src/main/resources/fabric.mod.json
Labels: bug, enhancement

#86 fix list insert trick
  src/main/java/dev/enjarai/trickster/spell/trick/list/ListInsertTrick.java
Labels: bug

#89 Fancy Fragments
  src/client/java/dev/enjarai/trickster/render/SpellCircleRenderer.java
  src/client/java/dev/enjarai/trickster/render/fragment/BlockTypeRenderer.java
  src/client/java/dev/enjarai/trickster/render/fragment/EntityRenderer.java
  src/client/java/dev/enjarai/trickster/render/fragment/FragmentRenderer.java
  src/client/java/dev/enjarai/trickster/render/fragment/ItemTypeRenderer.java
  src/client/java/dev/enjarai/trickster/render/fragment/PatternLiteralRenderer.java
  src/client/java/dev/enjarai/trickster/render/fragment/PatternRenderer.java
  src/main/java/dev/enjarai/trickster/mixin/accessor/WorldAccessor.java
  src/main/java/dev/enjarai/trickster/spell/fragment/EntityFragment.java
  src/main/resources/trickster.mixins.json
Labels: enhancement

#90 Improve fragment serialized data and remove Endec's faulty optionals
  gradle.properties
  src/client/java/dev/enjarai/trickster/net/ModClientNetworking.java
  src/client/java/dev/enjarai/trickster/screen/owo/SpellPreviewComponent.java
  src/main/java/dev/enjarai/trickster/EndecTomfoolery.java
  src/main/java/dev/enjarai/trickster/TricksterCommand.java
  src/main/java/dev/enjarai/trickster/block/ModularSpellConstructBlockEntity.java
  src/main/java/dev/enjarai/trickster/block/SpellConstructBlockEntity.java
  src/main/java/dev/enjarai/trickster/item/component/FragmentComponent.java
  src/main/java/dev/enjarai/trickster/item/component/ModComponents.java
  src/main/java/dev/enjarai/trickster/item/component/SpellCoreComponent.java
  src/main/java/dev/enjarai/trickster/spell/Fragment.java
  src/main/java/dev/enjarai/trickster/spell/SpellPart.java
  src/main/java/dev/enjarai/trickster/spell/execution/SerializedSpellInstruction.java
  src/main/java/dev/enjarai/trickster/spell/execution/executor/AtomicSpellExecutor.java
  src/main/java/dev/enjarai/trickster/spell/execution/executor/DefaultSpellExecutor.java
  src/main/java/dev/enjarai/trickster/spell/execution/executor/FoldingSpellExecutor.java
  src/main/java/dev/enjarai/trickster/spell/execution/executor/MessageListenerSpellExecutor.java
  src/main/java/dev/enjarai/trickster/spell/execution/executor/SpellExecutor.java
  src/main/java/dev/enjarai/trickster/spell/execution/executor/SpellExecutorType.java
Labels: bug

#85 Cotton PR: Mana trinket
  src/client/java/dev/enjarai/trickster/TricksterClient.java
  src/main/generated/.cache/27614340de28b382d5f7ae74366bcf39e2ac3aeb
  src/main/generated/.cache/3ac65fa3d3c37fa00307c1168fcecdd37a25c66a
  src/main/generated/.cache/61708f0ed37294451167e111af3b2b862215b6f8
  src/main/generated/.cache/79ef07c0320f2b1bff073a33f581b6ea484cf452
  src/main/generated/.cache/de828e1c0b483619cb31befb2371ade13f1a18a1
  src/main/generated/.cache/f158030e12b0d9d4165e4586179e424d8925bffa
  src/main/generated/assets/trickster/models/item/amethyst_whorl.json
  src/main/java/dev/enjarai/trickster/datagen/ModModelGenerator.java
  src/main/java/dev/enjarai/trickster/item/ManaAccessory.java
  src/main/java/dev/enjarai/trickster/item/ModItems.java
  src/main/java/dev/enjarai/trickster/spell/execution/source/PlayerSpellSource.java
  src/main/java/dev/enjarai/trickster/spell/mana/CachedInventoryManaPool.java
  src/main/java/dev/enjarai/trickster/spell/mana/PlayerManaPool.java
  src/main/java/dev/enjarai/trickster/spell/mana/generation/PlayerManaHandler.java
  src/main/java/dev/enjarai/trickster/spell/trick/mana/PushManaTrick.java
  src/main/resources/assets/trickster/lang/en_us.yml
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/amethyst_whorl.md
  src/main/resources/assets/trickster/textures/item/amethyst_whorl.png
  src/main/resources/data/accessories/tags/item/necklace.json
  src/main/resources/data/trickster/recipe/amethyst_whorl.json
Labels: enhancement

#92 Knot charging array
  src/client/java/dev/enjarai/trickster/TricksterClient.java
  src/client/java/dev/enjarai/trickster/render/ChargingArrayBlockEntityRenderer.java
  src/main/generated/.cache/27614340de28b382d5f7ae74366bcf39e2ac3aeb
  src/main/generated/.cache/3ac65fa3d3c37fa00307c1168fcecdd37a25c66a
  src/main/generated/.cache/61708f0ed37294451167e111af3b2b862215b6f8
  src/main/generated/.cache/79ef07c0320f2b1bff073a33f581b6ea484cf452
  src/main/generated/.cache/de828e1c0b483619cb31befb2371ade13f1a18a1
  src/main/generated/.cache/f158030e12b0d9d4165e4586179e424d8925bffa
  src/main/generated/assets/trickster/blockstates/charging_array.json
  src/main/generated/assets/trickster/models/item/charging_array.json
  src/main/java/dev/enjarai/trickster/block/ChargingArrayBlock.java
  src/main/java/dev/enjarai/trickster/block/ChargingArrayBlockEntity.java
  src/main/java/dev/enjarai/trickster/block/ModBlocks.java
  src/main/java/dev/enjarai/trickster/datagen/ModModelGenerator.java
  src/main/java/dev/enjarai/trickster/item/ModItems.java
  src/main/resources/assets/trickster/lang/en_us.yml
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/charging_array.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/items/knots.md
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/tutorials/2_mana_basics.md
  src/main/resources/assets/trickster/models/block/charging_array.json
  src/main/resources/assets/trickster/textures/block/charging_array_bottom.png
  src/main/resources/assets/trickster/textures/block/charging_array_side.png
  src/main/resources/assets/trickster/textures/block/charging_array_top.png
  src/main/resources/data/trickster/recipe/charging_array.json
Labels: enhancement

#98 Entity displacement
  src/client/java/dev/enjarai/trickster/mixin/client/InGameHudMixin.java
  src/main/java/dev/enjarai/trickster/TricksterCommand.java
  src/main/java/dev/enjarai/trickster/cca/DisplacementComponent.java
  src/main/java/dev/enjarai/trickster/cca/GraceComponent.java
  src/main/java/dev/enjarai/trickster/cca/ModEntityComponents.java
  src/main/java/dev/enjarai/trickster/mixin/LivingEntityMixin.java
  src/main/java/dev/enjarai/trickster/spell/blunder/EntityCannotBeDisplacedBlunder.java
  src/main/java/dev/enjarai/trickster/spell/trick/Tricks.java
  src/main/java/dev/enjarai/trickster/spell/trick/entity/DisplaceEntityTrick.java
  src/main/resources/assets/trickster/lang/en_us.yml
  src/main/resources/assets/trickster/lavender/entries/tome_of_tomfoolery/ploys/entity.md
  src/main/resources/data/trickster/tags/entity_type/irrepressible.json
  src/main/resources/fabric.mod.json
Labels: enhancement
